### ISSUE TITLE
automated linearization in python-mip

### ISSUE THREAD

**Issue by h-g-s** [pabloazurduy/qp-mip#1]
Hi, just found your example, really nice ! Added to a list of python-mip examples:
https://github.com/pabloazurduy/qp-mip  please feel free to change the description/authorsip. 
BTW, do you think that it would be interesting to add some automated linearization technique to python-mip ?

**Comment by pabloazurduy** [comment]
Hi Haroldo ! many thanks! yes I wrote this code as a part of a medium article, more than happy to contribute. Thanks for your awesome library. TBH I was trying to solve another [problem](https://github.com/coin-or/python-mip/issues/58#issuecomment-615314245) first (I think that the QP might take a little bit longer to implement) . I was trying to implement an IIS finder module. Im still writing a minimum example... anyway, Is there a way to contact you ? 
many thanks for the awesome library !

**Comment by h-g-s** [comment]
Great, could you provide the link of the medium article ? 
IIS is irreducible infeasible set ?  this would be enormously useful !
you can contact me  at   haroldo@ufop.edu.br   or  haroldo.santos@gmail.com

**Comment by pabloazurduy** [comment]
sure! [medium post](https://towardsdatascience.com/solving-a-quadratic-problem-qp-in-an-open-source-linear-solver-56ed6bb468e8?source=friends_link&sk=93e4433811ed4efc74bd393fe1dffa85)  
many thanks ! let's talk 😄
